# Generated by Django 3.1 on 2020-08-31 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_profile_single_dep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='single_dep',
            new_name='department',
        ),
    ]
