# Generated by Django 3.1 on 2020-09-04 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200831_1857'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Machine', 'Machine'), ('Weapon', 'Weapon'), ('Navigation', 'Navigation'), ('Soldier', 'Soldier')], default='Soldier', max_length=100),
        ),
    ]
