# Generated by Django 3.1 on 2020-09-04 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200904_1515'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.CharField(choices=[('OR-4', 'Corporal'), ('OR-5', 'Sergeant'), ('OR-6', 'Staff Sergeant'), ('OF-1', 'Lieutenant'), ('OF-2', 'Captain')], default='OR-4', max_length=100),
        ),
    ]
