# Generated by Django 3.1 on 2020-09-21 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('todo_list', '0008_auto_20200921_1036'),
        ('users', '0005_profile_rank'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='division',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='todo_list.department'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='department',
            field=models.CharField(choices=[('Electronics', 'Electronics'), ('Machine', 'Machine'), ('Weapon', 'Weapon'), ('Navigation', 'Navigation'), ('Soldier', 'Soldier')], default=1, max_length=100),
        ),
    ]
