# Generated by Django 3.1 on 2020-09-04 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_rank'),
        ('todo_list', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='todolist',
            name='responsibles',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='users.profile'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='status',
            field=models.CharField(choices=[('Not Seen Yet', 'Not Seen Yet'), ('Working on it', 'Working on it'), ('Done', 'Done'), ('Stuck', 'Stuck')], default='Not Seen Yet', max_length=100),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2020-09-04'),
        ),
        migrations.AlterField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2020-09-04'),
        ),
    ]
