# Generated by Django 3.1 on 2020-09-21 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('todo_list', '0007_auto_20200921_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='responsibles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to=settings.AUTH_USER_MODEL),
        ),
    ]
