# Generated by Django 3.1 on 2020-09-21 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_auto_20200921_1145'),
        ('todo_list', '0008_auto_20200921_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todolist',
            name='responsibles',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsible', to='users.profile'),
        ),
    ]
